export const CACHE_USERNAME = 'CACHE_USERNAME'
export const CACHE_ADMIN_STATUS = 'CACHE_ADMIN_STATUS'
export const POST_USER_PERMISSON_ERROR = 'POST_USER_PERMISSON_ERROR'
export const CLEAR_USER_PERMISSION_ERROR = 'CLEAR_USER_PERMISSION_ERROR'
export const CACHE_USER_PENDING_REQUESTS = 'CACHE_USER_PENDING_REQUESTS'
export const CACHE_USER_REQUESTS_AWAITING_REVIEW = 'CACHE_USER_REQUESTS_AWAITING_REVIEW'

export const FETCHING_STARTUP_DATA = 'FETCHING_STARTUP_DATA'
export const RETRIEVED_STARTUP_DATA = 'RETRIEVED_STARTUP_DATA'

export const CACHE_ADMIN_PENDING_REQUESTS = 'CACHE_ADMIN_PENDING_RQUESTS'

export const DISPLAY_REQUEST_FORM = 'DISPLAY_REQUEST_FORM'
export const CLEAR_CURRENT_FORM = 'CLEAR_CURRENT_FORM'
export const MARK_SUBMISSION_ATTEMPTED = 'MARK_SUBMISSION_ATTEMPTED'
export const UPDATE_FORM_DATA = 'UPDATE_FORM_DATA'
