export const CACHE_USERNAME = 'CACHE_USERNAME'
export const CACHE_ADMIN_STATUS = 'CACHE_ADMIN_STATUS'
export const POST_USER_PERMISSON_ERROR = 'POST_USER_PERMISSON_ERROR'
export const CLEAR_USER_PERMISSION_ERROR = 'CLEAR_USER_PERMISSION_ERROR'
export const CACHE_USER_PENDING_REQUESTS = 'CACHE_USER_PENDING_REQUESTS'
export const CACHE_USER_REQUESTS_AWAITING_REVIEW = 'CACHE_USER_REQUESTS_AWAITING_REVIEW'

export const FETCHING_STARTUP_DATA = 'FETCHING_STARTUP_DATA'
export const RETRIEVED_STARTUP_DATA = 'RETRIEVED_STARTUP_DATA'

export const CACHE_ADMIN_PENDING_REQUESTS = 'CACHE_ADMIN_PENDING_RQUESTS'

export const DISPLAY_REQUEST_FORM = 'DISPLAY_REQUEST_FORM'
export const DISPLAY_NEW_REQUEST_FORM = 'DISPLAY_NEW_REQUEST_FORM'
export const CLEAR_CURRENT_FORM = 'CLEAR_CURRENT_FORM'
export const MARK_SUBMISSION_ATTEMPTED = 'MARK_SUBMISSION_ATTEMPTED'
export const UPDATE_FORM_BATCH_DATA = 'UPDATE_FORM_BATCH_DATA'
export const UPDATE_FORM_BOX_GROUP_DATA = 'UPDATE_FORM_BOX_GROUP_DATA'
export const TOGGLE_BOX_LIST_VISIBILTY = 'TOGGLE_BOX_LIST_VISIBILTY'
export const ADD_BOXES_TO_REQUEST = 'ADD_BOXES_TO_REQUEST'
export const UPDATE_FORM_SINGLE_BOX_DATA = 'UPDATE_FORM_SINGLE_BOX_DATA'
export const MARK_ADD_BOXES_ATTEMPTED = 'MARK_ADD_BOXES_ATTEMPTED'
export const SUBMIT_CURRENT_FORM_FOR_APPROVAL = 'SUBMIT_CURRENT_FORM_FOR_APPROVAL'
export const RETURN_CURRENT_FORM_TO_USER = 'RETURN_CURRENT_FORM_TO_USER'
export const ARCHIVE_CURRENT_FORM = 'ARCHIVE_CURRENT_FORM'
export const UPDATE_CURRENT_FORM_STATUS = 'UPDATE_CURRENT_FORM_STATUS'
export const DISPLAY_COMMENT_INPUT = 'DISPLAY_COMMENT_INPUT'
export const UPDATE_FORM_ADMIN_COMMENTS = 'UPDATE_FORM_ADMIN_COMMENTS'
export const REMOVE_ADMIN_COMMENT = 'REMOVE_ADMIN_COMMENT'


// general action flags
export const PENDING = '_PENDING'
export const FULFILLED = '_FULFILLED'
